In [ ]:
# Question 1
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


# Load the dataset from url
url = "https://raw.githubusercontent.com/trojrobert/Classification-of-heart-disease-uci-data-/master/heart.csv"
df = pd.read_csv(url)

Load the dataset from CSV file
df = pd.read_csv('heart_disease.csv')

from sklearn.datasets import load_heart_disease
data = load_heart_disease()
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target


print(f"Dataset Shape: {df.shape}")
print(f"Number of Rows (Records): {df.shape[0]}")
print(f"Number of Columns (Features): {df.shape[1]}")

Dataset Shape: (303, 14)
Number of Rows (Records): 303
Number of Columns (Features): 14

In [2]:
# Question 2
print(f"Column names:\n{df.columns}")
# print(f"Column names:\n{df.keys()}")
print(f"Column names type: {type(df.columns)}")

print(f"\nColumn names as list:\n{df.columns.tolist()}")

print("\nColumn names with index numbers:")
for index, column in enumerate(df.columns):
    print(f"{index}: {column}")
    

# pd.set_option('display.max_column', None)
# pd.set_option('display.max_colwidth', None)
# pd.set_option('display.width', 1000)
# print(df.head(2))

from IPython.display import display
display(df.head(2))

Column names:
Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='str')
Column names type: <class 'pandas.Index'>

Column names as list:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target']

Column names with index numbers:
0: age
1: sex
2: cp
3: trestbps
4: chol
5: fbs
6: restecg
7: thalach
8: exang
9: oldpeak
10: slope
11: ca
12: thal
13: target

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1

In [3]:
# Question 3
# Method 1: Display data types using .dtypes attribute
print("Data types of each column: ")
print(df.dtypes)

# Method 2: Display data types in a more readable format
print("\nData Types (Detailed View):")
for column in df.columns:
    print(f"{column}: {df[column].dtype}")

# Method 3: Count columns by data type
print("\nCount of columns by data type:")
print(df.dtypes.value_counts())

# Method 4: Display data type information using info()
print("\nDetailed Data Type Information (info):")
df.info()

Data types of each column:
age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

Data Types (Detailed View):
age: int64
sex: int64
cp: int64
trestbps: int64
chol: int64
fbs: int64
restecg: int64
thalach: int64
exang: int64
oldpeak: float64
slope: int64
ca: int64
thal: int64
target: int64

Count of columns by data type:
int64      13
float64     1
Name: count, dtype: int64

Detailed Data Type Information (info):
<class 'pandas.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [5]:
print(f"The range of 'age' column: ({min(df['age'])}, {max(df['age'])})")
print(f"The range of 'trestbps' column: ({min(df['trestbps'])}, {max(df['trestbps'])})")
print(f"The range of 'chol' column: ({min(df['chol'])}, {max(df['chol'])})")
print(f"The range of 'thalach' column: ({min(df['thalach'])}, {max(df['thalach'])})")
print(f"The range of 'oldpeak' column: ({min(df['oldpeak'])}, {max(df['oldpeak'])})")

The range of 'age' column: (29, 77)
The range of 'trestbps' column: (94, 200)
The range of 'chol' column: (126, 564)
The range of 'thalach' column: (71, 202)
The range of 'oldpeak' column: (0.0, 6.2)

In [10]:
print("Discrete/Categorical values:")
print(f"sex:\t{set(df['sex'])}")
print(f"cp:\t{set(df['cp'])}")
print(f"fbs:\t{set(df['fbs'])}")
print(f"restecg:\t{set(df['restecg'])}")
print(f"exang:\t{set(df['exang'])}")
print(f"slope:\t{set(df['slope'])}")
print(f"ca:\t{set(df['ca'])}")
print(f"thal:\t{set(df['thal'])}")

Discrete/Categorical values:
sex:	{0, 1}
cp:	{0, 1, 2, 3}
fbs:	{0, 1}
restecg:	{0, 1, 2}
exang:	{0, 1}
slope:	{0, 1, 2}
ca:	{0, 1, 2, 3, 4}
thal:	{0, 1, 2, 3}

In [14]:
# Question 4
feature_nature_types = {
    'age': 'Numerical (Continuous)',
    'sex': 'Binary (Categorical)',
    'cp': 'Categorical (Nominal)',
    'trestbps': 'Numerical (Continuous)',
    'chol': 'Numerical (Continuous)',
    'fbs': 'Binary (Categorical)',
    'restecg': 'Categorical (Ordinal)',
    'thalach': 'Numerical (Continuous)',
    'exang': 'Binary (Categorical)',
    'oldpeak': 'Numerical (Continuous)',
    'slope': 'Categorical (Ordinal)',
    'ca': 'Categorical (Ordinal)',
    'thal': 'Categorical (Ordinal)',
    'target': 'Binary (Categorical)'
}

for feature, feature_type in feature_nature_types.items():
    print(f"{feature}: {feature_type}")

age: Numerical (Continuous)
sex: Binary (Categorical)
cp: Categorical (Nominal)
trestbps: Numerical (Continuous)
chol: Numerical (Continuous)
fbs: Binary (Categorical)
restecg: Categorical (Ordinal)
thalach: Numerical (Continuous)
exang: Binary (Categorical)
oldpeak: Numerical (Continuous)
slope: Categorical (Ordinal)
ca: Categorical (Ordinal)
thal: Categorical (Ordinal)
target: Binary (Categorical)

In [18]:
# Question 5

# Create a comprehensive business dictionary for each feature
# This dictionary translates technical column names to business/medical meanings
business_meaning = {
    'age': {
        'technical': 'Age of patient in years',
        'business': 'سن بیمار بر حسب سال - یکی از مهم‌ترین عوامل خطر در بیماری‌های قلبی',
        'medical_significance': 'با افزایش سن، خطر بیماری‌های قلبی عروقی به طور قابل‌توجهی افزایش می‌یابد',
        'range': '29 to 77 years',
        'business_impact': 'برای شناسایی گروه‌های سنی پرخطر و طراحی برنامه‌های غربالگری سن‌محور'
    },
    'sex': {
        'technical': 'Gender of patient (0 = female, 1 = male)',
        'business': 'جنسیت بیمار - مرد یا زن',
        'medical_significance': 'مردان در سنین پایین‌تر نسبت به زنان در معرض خطر بیشتری هستند',
        'range': '0 or 1',
        'business_impact': 'برای طراحی برنامه‌های پیشگیری متناسب با جنسیت و آگاهی از تفاوت‌های جنسیتی'
    },
    'cp': {
        'technical': 'Chest pain type (0 = typical angina, 1 = atypical angina, 2 = non-anginal pain, 3 = asymptomatic)',
        'business': 'نوع درد قفسه سینه - یکی از مهم‌ترین علائم بالینی بیماری قلبی',
        'medical_significance': 'درد تیپیک آنژین (نوع ۰) قوی‌ترین ارتباط را با بیماری قلبی دارد',
        'range': '0 to 3',
        'business_impact': 'کمک به پزشکان برای تشخیص اولیه بر اساس نوع درد و اولویت‌بندی بیماران'
    },
    'trestbps': {
        'technical': 'Resting blood pressure (in mm Hg on admission to the hospital)',
        'business': 'فشار خون در حالت استراحت - یکی از علائم حیاتی اصلی',
        'medical_significance': 'فشار خون بالا یکی از مهم‌ترین عوامل خطر برای بیماری‌های قلبی است',
        'range': '94 to 200 mm Hg',
        'business_impact': 'شناسایی بیماران با فشار خون کنترل‌نشده و نیازمند پیگیری فوری'
    },
    'chol': {
        'technical': 'Serum cholesterol in mg/dl',
        'business': 'میزان کلسترول خون - شاخص مهم سلامت قلب و عروق',
        'medical_significance': 'کلسترول بالا باعث تشکیل پلاک در عروق و افزایش خطر حمله قلبی می‌شود',
        'range': '126 to 564 mg/dl',
        'business_impact': 'شناسایی بیماران با کلسترول بالا برای تغییر سبک زندگی و درمان دارویی'
    },
    'fbs': {
        'technical': 'Fasting blood sugar > 120 mg/dl (0 = false, 1 = true)',
        'business': 'قند خون ناشتا - شاخص مهم برای دیابت',
        'medical_significance': 'قند خون بالا و دیابت یکی از عوامل خطر اصلی بیماری قلبی است',
        'range': '0 or 1',
        'business_impact': 'شناسایی بیماران دیابتی یا پیش‌دیابتی که نیاز به مدیریت همزمان قند و سلامت قلب دارند'
    },
    'restecg': {
        'technical': 'Resting electrocardiographic results (0 = normal, 1 = ST-T wave abnormality, 2 = left ventricular hypertrophy)',
        'business': 'نتیجه نوار قلب در حالت استراحت - یک تست تشخیصی غیرتهاجمی',
        'medical_significance': 'ناهنجاری‌های نوار قلب نشان‌دهنده مشکلات الکتریکی یا ساختاری قلب است',
        'range': '0 to 2',
        'business_impact': 'ارائه اطلاعات اولیه درباره سلامت قلب قبل از انجام تست‌های ورزشی یا تهاجمی'
    },
    'thalach': {
        'technical': 'Maximum heart rate achieved during exercise test',
        'business': 'حداکثر ضربان قلب در طول تست ورزش - شاخص عملکرد قلبی-عروقی',
        'medical_significance': 'ضربان قلب پایین‌تر از حد انتظار در حین ورزش، نشانه مشکل قلبی است',
        'range': '71 to 202 bpm',
        'business_impact': 'ارزیابی ظرفیت عملکردی قلب و تشخیص زودهنگام نارسایی قلبی'
    },
    'exang': {
        'technical': 'Exercise induced angina (0 = no, 1 = yes)',
        'business': 'درد قفسه سینه ناشی از ورزش - یک علامت هشداردهنده مهم',
        'medical_significance': 'بروز آنژین در حین ورزش نشان‌دهنده کمبود اکسیژن رسانی به قلب است',
        'range': '0 or 1',
        'business_impact': 'تشخیص بیمارانی که در معرض خطر حمله قلبی در حین فعالیت هستند'
    },
    'oldpeak': {
        'technical': 'ST depression induced by exercise relative to rest (in mm)',
        'business': 'افت قطعه ST در نوار قلب در حین ورزش - یک شاخص تشخیصی مهم',
        'medical_significance': 'افت بیشتر ST نشان‌دهنده ایسکمی (کمبود خون) شدیدتر قلبی است',
        'range': '0 to 6.2 mm',
        'business_impact': 'ارزیابی شدت بیماری و نیاز به مداخلات درمانی فوری'
    },
    'slope': {
        'technical': 'The slope of the peak exercise ST segment (0 = upsloping, 1 = flat, 2 = downsloping)',
        'business': 'شیب قطعه ST در نوار قلب حین ورزش - نشان‌دهنده پاسخ قلب به استرس',
        'medical_significance': 'شیب نزولی (نوع ۲) با خطر بالاتر بیماری قلبی مرتبط است',
        'range': '0 to 2',
        'business_impact': 'تشخیص بیماران با پاسخ غیرطبیعی قلب به ورزش و نیاز به بررسی دقیق‌تر'
    },
    'ca': {
        'technical': 'Number of major vessels (0-4) colored by fluoroscopy',
        'business': 'تعداد رگ‌های اصلی قلب که در آنژیوگرافی مسدود شده‌اند',
        'medical_significance': 'تعداد بیشتر رگ‌های بسته نشان‌دهنده بیماری شدیدتر عروق کرونر است',
        'range': '0 to 4',
        'business_impact': 'ارزیابی شدت بیماری و تصمیم‌گیری برای درمان تهاجمی (آنژیوپلاستی یا جراحی بای‌پس)'
    },
    'thal': {
        'technical': 'Thalassemia (3 = normal, 6 = fixed defect, 7 = reversible defect)',
        'business': 'نوع تالاسمی یا نقص در خون‌رسانی به قلب - یک شاخص تشخیصی',
        'medical_significance': 'نقص برگشت‌پذیر (نوع ۷) نشان‌دهنده ایسکمی قابل درمان است',
        'range': '0 to 7',
        'business_impact': 'تشخیص بیماران با نقص خون‌رسانی که ممکن است از درمان‌های مداخله‌ای بهره‌مند شوند'
    },
    'target': {
        'technical': 'Presence of heart disease (0 = no disease, 1 = has disease)',
        'business': 'تشخیص نهایی بیماری قلبی - متغیر هدف سیستم هوشمند',
        'medical_significance': 'نتیجه نهایی تشخیص بر اساس مجموعه‌ای از تست‌ها و معاینات',
        'range': '0 or 1',
        'business_impact': 'پیش‌بینی دقیق این متغیر می‌تواند از انجام تست‌های پرهزینه و تهاجمی جلوگیری کند'
    }
}

# Group features by business category
demographic_features = ['age', 'sex']
clinical_features = ['trestbps', 'chol', 'fbs', 'thalach', 'oldpeak']
symptom_features = ['cp', 'exang']
diagnostic_features = ['restecg', 'slope', 'ca', 'thal']
target_feature = ['target']

for column, details in business_meaning.items():
    print(f"FEATURE: {column.upper()}")
    print(f"\t- Technical Name : {details['technical']}")
    print(f"\t- Business Meaning: {details['business']}")
    print(f"\t- Medical Significance: {details['medical_significance']}")
    print(f"\t- Range: {details['range']}")
    print(f"\t- Business Impact: {details['business_impact']}")
    print("\n")
    
print("\nDEMOGRAPHIC FEATURES (Patient Information):")
for feature in demographic_features:
    print(f"\t- {feature}: {business_meaning[feature]['business'].split('-')[0].strip()}")

print("\nCLINICAL MEASUREMENTS (Test Results):")
for feature in clinical_features:
    print(f"\t- {feature}: {business_meaning[feature]['business'].split('-')[0].strip()}")

print("\nSYMPTOM FEATURES (Patient Complaints):")
for feature in symptom_features:
    print(f"\t- {feature}: {business_meaning[feature]['business'].split('-')[0].strip()}")

print("\nDIAGNOSTIC FEATURES (Advanced Tests):")
for feature in diagnostic_features:
    print(f"\t- {feature}: {business_meaning[feature]['business'].split('-')[0].strip()}")

print("\nTARGET VARIABLE (Prediction Goal):")
for feature in target_feature:
    print(f"\t- {feature}: {business_meaning[feature]['business']}")

FEATURE: AGE
	- Technical Name : Age of patient in years
	- Business Meaning: سن بیمار بر حسب سال - یکی از مهم‌ترین عوامل خطر در بیماری‌های قلبی
	- Medical Significance: با افزایش سن، خطر بیماری‌های قلبی عروقی به طور قابل‌توجهی افزایش می‌یابد
	- Range: 29 to 77 years
	- Business Impact: برای شناسایی گروه‌های سنی پرخطر و طراحی برنامه‌های غربالگری سن‌محور


FEATURE: SEX
	- Technical Name : Gender of patient (0 = female, 1 = male)
	- Business Meaning: جنسیت بیمار - مرد یا زن
	- Medical Significance: مردان در سنین پایین‌تر نسبت به زنان در معرض خطر بیشتری هستند
	- Range: 0 or 1
	- Business Impact: برای طراحی برنامه‌های پیشگیری متناسب با جنسیت و آگاهی از تفاوت‌های جنسیتی


FEATURE: CP
	- Technical Name : Chest pain type (0 = typical angina, 1 = atypical angina, 2 = non-anginal pain, 3 = asymptomatic)
	- Business Meaning: نوع درد قفسه سینه - یکی از مهم‌ترین علائم بالینی بیماری قلبی
	- Medical Significance: درد تیپیک آنژین (نوع ۰) قوی‌ترین ارتباط را با بیماری قلبی دارد
	- Range: 0 to 3
	- Business Impact: کمک به پزشکان برای تشخیص اولیه بر اساس نوع درد و اولویت‌بندی بیماران


FEATURE: TRESTBPS
	- Technical Name : Resting blood pressure (in mm Hg on admission to the hospital)
	- Business Meaning: فشار خون در حالت استراحت - یکی از علائم حیاتی اصلی
	- Medical Significance: فشار خون بالا یکی از مهم‌ترین عوامل خطر برای بیماری‌های قلبی است
	- Range: 94 to 200 mm Hg
	- Business Impact: شناسایی بیماران با فشار خون کنترل‌نشده و نیازمند پیگیری فوری


FEATURE: CHOL
	- Technical Name : Serum cholesterol in mg/dl
	- Business Meaning: میزان کلسترول خون - شاخص مهم سلامت قلب و عروق
	- Medical Significance: کلسترول بالا باعث تشکیل پلاک در عروق و افزایش خطر حمله قلبی می‌شود
	- Range: 126 to 564 mg/dl
	- Business Impact: شناسایی بیماران با کلسترول بالا برای تغییر سبک زندگی و درمان دارویی


FEATURE: FBS
	- Technical Name : Fasting blood sugar > 120 mg/dl (0 = false, 1 = true)
	- Business Meaning: قند خون ناشتا - شاخص مهم برای دیابت
	- Medical Significance: قند خون بالا و دیابت یکی از عوامل خطر اصلی بیماری قلبی است
	- Range: 0 or 1
	- Business Impact: شناسایی بیماران دیابتی یا پیش‌دیابتی که نیاز به مدیریت همزمان قند و سلامت قلب دارند


FEATURE: RESTECG
	- Technical Name : Resting electrocardiographic results (0 = normal, 1 = ST-T wave abnormality, 2 = left ventricular hypertrophy)
	- Business Meaning: نتیجه نوار قلب در حالت استراحت - یک تست تشخیصی غیرتهاجمی
	- Medical Significance: ناهنجاری‌های نوار قلب نشان‌دهنده مشکلات الکتریکی یا ساختاری قلب است
	- Range: 0 to 2
	- Business Impact: ارائه اطلاعات اولیه درباره سلامت قلب قبل از انجام تست‌های ورزشی یا تهاجمی


FEATURE: THALACH
	- Technical Name : Maximum heart rate achieved during exercise test
	- Business Meaning: حداکثر ضربان قلب در طول تست ورزش - شاخص عملکرد قلبی-عروقی
	- Medical Significance: ضربان قلب پایین‌تر از حد انتظار در حین ورزش، نشانه مشکل قلبی است
	- Range: 71 to 202 bpm
	- Business Impact: ارزیابی ظرفیت عملکردی قلب و تشخیص زودهنگام نارسایی قلبی


FEATURE: EXANG
	- Technical Name : Exercise induced angina (0 = no, 1 = yes)
	- Business Meaning: درد قفسه سینه ناشی از ورزش - یک علامت هشداردهنده مهم
	- Medical Significance: بروز آنژین در حین ورزش نشان‌دهنده کمبود اکسیژن رسانی به قلب است
	- Range: 0 or 1
	- Business Impact: تشخیص بیمارانی که در معرض خطر حمله قلبی در حین فعالیت هستند


FEATURE: OLDPEAK
	- Technical Name : ST depression induced by exercise relative to rest (in mm)
	- Business Meaning: افت قطعه ST در نوار قلب در حین ورزش - یک شاخص تشخیصی مهم
	- Medical Significance: افت بیشتر ST نشان‌دهنده ایسکمی (کمبود خون) شدیدتر قلبی است
	- Range: 0 to 6.2 mm
	- Business Impact: ارزیابی شدت بیماری و نیاز به مداخلات درمانی فوری


FEATURE: SLOPE
	- Technical Name : The slope of the peak exercise ST segment (0 = upsloping, 1 = flat, 2 = downsloping)
	- Business Meaning: شیب قطعه ST در نوار قلب حین ورزش - نشان‌دهنده پاسخ قلب به استرس
	- Medical Significance: شیب نزولی (نوع ۲) با خطر بالاتر بیماری قلبی مرتبط است
	- Range: 0 to 2
	- Business Impact: تشخیص بیماران با پاسخ غیرطبیعی قلب به ورزش و نیاز به بررسی دقیق‌تر


FEATURE: CA
	- Technical Name : Number of major vessels (0-4) colored by fluoroscopy
	- Business Meaning: تعداد رگ‌های اصلی قلب که در آنژیوگرافی مسدود شده‌اند
	- Medical Significance: تعداد بیشتر رگ‌های بسته نشان‌دهنده بیماری شدیدتر عروق کرونر است
	- Range: 0 to 4
	- Business Impact: ارزیابی شدت بیماری و تصمیم‌گیری برای درمان تهاجمی (آنژیوپلاستی یا جراحی بای‌پس)


FEATURE: THAL
	- Technical Name : Thalassemia (3 = normal, 6 = fixed defect, 7 = reversible defect)
	- Business Meaning: نوع تالاسمی یا نقص در خون‌رسانی به قلب - یک شاخص تشخیصی
	- Medical Significance: نقص برگشت‌پذیر (نوع ۷) نشان‌دهنده ایسکمی قابل درمان است
	- Range: 0 to 7
	- Business Impact: تشخیص بیماران با نقص خون‌رسانی که ممکن است از درمان‌های مداخله‌ای بهره‌مند شوند


FEATURE: TARGET
	- Technical Name : Presence of heart disease (0 = no disease, 1 = has disease)
	- Business Meaning: تشخیص نهایی بیماری قلبی - متغیر هدف سیستم هوشمند
	- Medical Significance: نتیجه نهایی تشخیص بر اساس مجموعه‌ای از تست‌ها و معاینات
	- Range: 0 or 1
	- Business Impact: پیش‌بینی دقیق این متغیر می‌تواند از انجام تست‌های پرهزینه و تهاجمی جلوگیری کند



DEMOGRAPHIC FEATURES (Patient Information):
	- age: سن بیمار بر حسب سال
	- sex: جنسیت بیمار

CLINICAL MEASUREMENTS (Test Results):
	- trestbps: فشار خون در حالت استراحت
	- chol: میزان کلسترول خون
	- fbs: قند خون ناشتا
	- thalach: حداکثر ضربان قلب در طول تست ورزش
	- oldpeak: افت قطعه ST در نوار قلب در حین ورزش

SYMPTOM FEATURES (Patient Complaints):
	- cp: نوع درد قفسه سینه
	- exang: درد قفسه سینه ناشی از ورزش

DIAGNOSTIC FEATURES (Advanced Tests):
	- restecg: نتیجه نوار قلب در حالت استراحت
	- slope: شیب قطعه ST در نوار قلب حین ورزش
	- ca: تعداد رگ‌های اصلی قلب که در آنژیوگرافی مسدود شده‌اند
	- thal: نوع تالاسمی یا نقص در خون‌رسانی به قلب

TARGET VARIABLE (Prediction Goal):
	- target: تشخیص نهایی بیماری قلبی - متغیر هدف سیستم هوشمند

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', 20)
sns.set_style('whitegrid')
plt.rcParams['figure.figsize'] = (8, 5)

df = pd.read_csv('heart.csv')
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

بخش اول

شناخت اولیه دیتاست

سوال 1

چند سطر و چند ستون در دیتاست وجود دارد؟

In [8]:
#ًquestion 1
rows, cols = df.shape
print(f"تعداد سطرها: {rows}")
print(f"تعداد ستون‌ها: {cols}")

تعداد سطرها: 303
تعداد ستون‌ها: 14

سوال 2

نام تمام ستون‌ها چیست؟

In [ ]:
#ًquestion 2
list(df.columns)

['age',
 'sex',
 'cp',
 'trestbps',
 'chol',
 'fbs',
 'restecg',
 'thalach',
 'exang',
 'oldpeak',
 'slope',
 'ca',
 'thal',
 'target']

سوال 3

نوع داده هر ستون چیست؟

In [ ]:
#ًquestion 3
df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

سوال 4

برای هر ستون تعیین کنید:

عددی

دسته‌ای

دودویی

In [ ]:
#ًquestion 4
column_types = pd.DataFrame({
    'column': ['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg',
               'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
    'type': ['numerical', 'binary', 'categorical', 'numerical', 'numerical', 'binary', 'categorical',
             'numerical', 'binary', 'numerical', 'categorical', 'categorical', 'categorical', 'binary (target)']
})
column_types

      column             type
0        age        numerical
1        sex           binary
2         cp      categorical
3   trestbps        numerical
4       chol        numerical
5        fbs           binary
6    restecg      categorical
7    thalach        numerical
8      exang           binary
9    oldpeak        numerical
10     slope      categorical
11        ca      categorical
12      thal      categorical
13    target  binary (target)

سوال 5

از دید کسب‌وکار هر ستون چه مفهومی دارد؟

In [12]:
#ًquestion 5
business_meaning = pd.DataFrame({
    'column': ['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg',
               'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
    'meaning': [
        'Age of the patient in years',
        'Gender (1 = male, 0 = female)',
        'Type of chest pain (0 to 3)',
        'Resting blood pressure (mm Hg)',
        'Serum cholesterol level (mg/dl)',
        'Fasting blood sugar > 120 mg/dl (1 = true, 0 = false)',
        'Resting electrocardiographic results (0, 1, 2)',
        'Maximum heart rate achieved during exercise test',
        'Exercise induced angina (1 = yes, 0 = no)',
        'ST depression induced by exercise relative to rest',
        'Slope of the peak exercise ST segment',
        'Number of major vessels colored by fluoroscopy (0-3)',
        'Thalium stress test result',
        'Presence of heart disease (1 = has disease, 0 = no disease)'
    ]
})
business_meaning

      column                                            meaning
0        age                        Age of the patient in years
1        sex                      Gender (1 = male, 0 = female)
2         cp                        Type of chest pain (0 to 3)
3   trestbps                     Resting blood pressure (mm Hg)
4       chol                    Serum cholesterol level (mg/dl)
5        fbs  Fasting blood sugar > 120 mg/dl (1 = true, 0 =...
6    restecg     Resting electrocardiographic results (0, 1, 2)
7    thalach   Maximum heart rate achieved during exercise test
8      exang          Exercise induced angina (1 = yes, 0 = no)
9    oldpeak  ST depression induced by exercise relative to ...
10     slope              Slope of the peak exercise ST segment
11        ca  Number of major vessels colored by fluoroscopy...
12      thal                         Thalium stress test result
13    target  Presence of heart disease (1 = has disease, 0 ...

بخش دوم

کیفیت داده

سوال 6

در هر ستون چند مقدار Null وجود دارد؟

In [13]:
#ًquestion 6
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

سوال 7

درصد داده‌های گمشده هر ستون چقدر است؟

In [ ]:
#ًquestion 7
missing_percent = df.isnull().sum() / len(df) * 100
missing_percent

age         0.0
sex         0.0
cp          0.0
trestbps    0.0
chol        0.0
fbs         0.0
restecg     0.0
thalach     0.0
exang       0.0
oldpeak     0.0
slope       0.0
ca          0.0
thal        0.0
target      0.0
dtype: float64

سوال 8

آیا رکورد تکراری وجود دارد؟

In [18]:
duplicate_count = df.duplicated().sum()
print("Are there duplicate rows?", duplicate_count)

df[df.duplicated()]

Are there duplicate rows? 1

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
164,38,1,2,138,175,0,1,173,0,0.0,2,4,2,1

سوال 9
اگر رکورد تکراری وجود دارد:

چند عدد است؟

چند درصد کل داده است؟

In [19]:
duplicate_count = df.duplicated().sum()
duplicate_percent = duplicate_count / len(df) * 100

print("Number of duplicate rows:", duplicate_count)
print("Percentage of total data:", duplicate_percent)

Number of duplicate rows: 1
Percentage of total data: 0.33003300330033003

بخش چهارم

تحلیل ویژگی‌های عددی

سوال 12

آمار توصیفی کامل ویژگی‌های عددی را استخراج کنید.

In [ ]:
numeric_cols = ['age', 'trestbps', 'chol', 'thalach', 'oldpeak']
df[numeric_cols].describe()

              age    trestbps        chol     thalach     oldpeak
count  303.000000  303.000000  303.000000  303.000000  303.000000
mean    54.366337  131.623762  246.264026  149.646865    1.039604
std      9.082101   17.538143   51.830751   22.905161    1.161075
min     29.000000   94.000000  126.000000   71.000000    0.000000
25%     47.500000  120.000000  211.000000  133.500000    0.000000
50%     55.000000  130.000000  240.000000  153.000000    0.800000
75%     61.000000  140.000000  274.500000  166.000000    1.600000
max     77.000000  200.000000  564.000000  202.000000    6.200000

سوال 13
برای هر ویژگی عددی:

میانگین

میانه

مد

را محاسبه کنید.

In [22]:
mean = df[numeric_cols].mean()
median = df[numeric_cols].median()
mode = df[numeric_cols].mode().iloc[0]

print("Mean:\n", mean)
print("Median:\n", median)
print("Mode:\n", mode)

Mean:
 age          54.366337
trestbps    131.623762
chol        246.264026
thalach     149.646865
oldpeak       1.039604
dtype: float64
Median:
 age          55.0
trestbps    130.0
chol        240.0
thalach     153.0
oldpeak       0.8
dtype: float64
Mode:
 age          58.0
trestbps    120.0
chol        197.0
thalach     162.0
oldpeak       0.0
Name: 0, dtype: float64

سوال 14
برای هر ویژگی عددی:

واریانس

انحراف معیار

را محاسبه کنید.

In [24]:
variance_op = df[numeric_cols].var()
std_op = df[numeric_cols].std()

print("Variance:\n", variance_op)
print("Standard Deviation:\n", std_op)

Variance:
 age           82.484558
trestbps     307.586453
chol        2686.426748
thalach      524.646406
oldpeak        1.348095
dtype: float64
Standard Deviation:
 age          9.082101
trestbps    17.538143
chol        51.830751
thalach     22.905161
oldpeak      1.161075
dtype: float64

بخش ششم

ارتباط ویژگی‌ها با هدف

سوال 22
بررسی کنید آیا افراد مسن‌تر بیشتر بیمار هستند؟

In [25]:
print(df.groupby('target')['age'].mean())

target
0    56.601449
1    52.496970
Name: age, dtype: float64